# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170914_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('no_followers', models.IntegerField(default=0)),
                ('no_following', models.IntegerField(default=0)),
                ('prefferedgenre', models.CharField(max_length=20)),
                ('followers', models.TextField(blank=True)),
                ('followingd', models.TextField(blank=True)),
            ],
        ),
    ]
