# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0006_auto_20170920_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='likes',
            new_name='like',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='followingd',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='no_followers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='no_following',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='music',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='music.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
