# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0007_auto_20171013_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='like',
        ),
        migrations.AddField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
