# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20171013_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
