# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20171014_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first',
            field=models.BooleanField(default=True),
        ),
    ]
