# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 08:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_userprofile_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='songphoto',
            field=models.FileField(upload_to='static/music/songimages'),
        ),
        migrations.AlterField(
            model_name='music',
            name='songupload',
            field=models.FileField(upload_to='static/music/songs', validators=[django.core.validators.FileExtensionValidator(['mp3', '.aac', 'mp4'])]),
        ),
    ]
