# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20171019_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='songphoto',
            field=models.FileField(upload_to='static/music/songimages', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'bmp', 'jpg'], 'file exteion not valid')]),
        ),
        migrations.AlterField(
            model_name='music',
            name='songupload',
            field=models.FileField(upload_to='static/music/songs', validators=[django.core.validators.FileExtensionValidator(['mp3', 'aac'], 'file extension not valid')]),
        ),
    ]
