# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20171019_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='songformat',
        ),
    ]
