# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20171022_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='likenum',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
