# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 15:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_music_likenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userphoto',
            field=models.ImageField(null=True, upload_to='static/music/userimages', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'bmp', 'jpg'], 'file exteion not valid')]),
        ),
    ]
